{% set name = "pynndescent" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7ffde0fb5b400741e055a9f7d377e3702e02250616834231f6c209e39aac24f5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools >=61.2
  run:
    - python
    - scikit-learn >=0.18
    - scipy >=1.0
    - numba >=0.55.0
    - llvmlite >=0.38
    - joblib >=0.11
    - numpy >=1.17

test:
  source_files:
    - pynndescent/tests
  imports:
    - pynndescent
    - pynndescent.distances
    - pynndescent.optimal_transport
    - pynndescent.rp_trees
    - pynndescent.sparse
    - pynndescent.sparse_nndescent
    - pynndescent.utils
  commands:
    - pip check
    # pyargs does not work, tests folder not in the site-packages dir.
    - pytest -v pynndescent/tests
  requires:
    - pip
    - pytest
    # [TODO]: Check if needed during next version bump
    # FIX for unit tests: The sokalmichener metric is deprecated since SciPy 1.15.0 and will be removed in SciPy 1.17.0
    - scipy <1.17

about:
  home: https://github.com/lmcinnes/pynndescent
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simple fast approximate nearest neighbor search
  description: |
    A Python nearest neighbor descent for approximate nearest neighbors.
    This is a relatively straightforward python implementation of
    Nearest Neighbor Descent for k-neighbor-graph construction and
    approximate nearest neighbor search.
  dev_url: https://github.com/lmcinnes/pynndescent
  doc_url: https://pynndescent.readthedocs.io

extra:
  recipe-maintainers:
    - lmcinnes
