{% set name = "pynndescent" %}
{% set version = "0.5.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d74254c0ee0a1eeec84597d5fe89fedcf778593eeabe32c2f97412934a9800fb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - importlib-metadata >=4.8.1  # [py<38]
    - joblib >=0.11
    - llvmlite >=0.30
    - numba >=0.51.2
    - numpy >=1.17
    - scikit-learn >=0.18
    - scipy >=1.0

test:
  source_files:
    - pynndescent/tests
  imports:
    - pynndescent
    - pynndescent.distances
    - pynndescent.optimal_transport
    - pynndescent.rp_trees
    - pynndescent.sparse
    - pynndescent.sparse_nndescent
    - pynndescent.utils
  commands:
    - pip check
    # pyargs does not work, tests folder not in the site-packages dir.
    - pytest -v pynndescent/tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/lmcinnes/pynndescent
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simple fast approximate nearest neighbor search
  description: |
    A Python nearest neighbor descent for approximate nearest neighbors. 
    This is a relatively straightforward python implementation of 
    Nearest Neighbor Descent for k-neighbor-graph construction and 
    approximate nearest neighbor search.
  dev_url: https://github.com/lmcinnes/pynndescent
  doc_url: https://pynndescent.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - lmcinnes