{% set name = "pynndescent" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7ffde0fb5b400741e055a9f7d377e3702e02250616834231f6c209e39aac24f5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools >=61.2
  run:
    - python
    - scikit-learn >=0.18
    - scipy >=1.0
    - numba >=0.55.0
    - llvmlite >=0.38
    - joblib >=0.11
    - numpy >=1.17

# E sklearn.utils._param_validation.InvalidParameterError: The 'metric' parameter of pairwise_distances must be a 
# str among {'l1', 'wminkowski', 'chebyshev', 'rogerstanimoto', 'precomputed', 'sokalsneath', 'braycurtis', 'correlation', 
# 'dice', 'jaccard', 'nan_euclidean', 'haversine', 'matching', 'euclidean', 'canberra', 'hamming', 'minkowski', 'yule', 
# 'sqeuclidean', 'seuclidean', 'manhattan', 'cityblock', 'russellrao', 'mahalanobis', 'cosine', 'l2'} or a callable. Got 'sokalmichener' instead.
{% set deselect_tests = " --deselect=pynndescent/tests/test_distances.py::test_binary_check" %}
{% set deselect_tests = deselect_tests + " --deselect=pynndescent/tests/test_distances.py::test_sparse_binary_check" %}
# E        ACTUAL: array([[ 0.      , 67.849031, 10.949829, 62.72757 , 45.5568  , 29.807874,
# E               70.065031, 48.540842, 27.665679, 28.211244, 26.883046, 26.883046],
# E              [67.849031,  0.      , 61.682592, 11.370837, 26.474672, 40.951435,...
# E        DESIRED: array([[ 0.      , 67.849031, 10.949829, 62.727569, 45.556799, 29.807874,
# E               70.065032, 48.54084 , 27.665678, 28.211243, 26.883046, 26.883046],
# E              [67.849031,  0.      , 61.682592, 11.370837, 26.474672, 40.951436,...
{% set deselect_tests = deselect_tests + " --deselect=pynndescent/tests/test_distances.py::test_seuclidean" %}

test:
  source_files:
    - pynndescent/tests
  imports:
    - pynndescent
    - pynndescent.distances
    - pynndescent.optimal_transport
    - pynndescent.rp_trees
    - pynndescent.sparse
    - pynndescent.sparse_nndescent
    - pynndescent.utils
  commands:
    - pip check
    # pyargs does not work, tests folder not in the site-packages dir.
    - pytest -v pynndescent/tests {{ deselect_tests }}
  requires:
    - pip
    - pytest

about:
  home: https://github.com/lmcinnes/pynndescent
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simple fast approximate nearest neighbor search
  description: |
    A Python nearest neighbor descent for approximate nearest neighbors.
    This is a relatively straightforward python implementation of
    Nearest Neighbor Descent for k-neighbor-graph construction and
    approximate nearest neighbor search.
  dev_url: https://github.com/lmcinnes/pynndescent
  doc_url: https://pynndescent.readthedocs.io

extra:
  recipe-maintainers:
    - lmcinnes
