travis:
  secure:
    BINSTAR_TOKEN: CmHril4lkj4MKnhaW8Q+jg5kfVRZHFGNZm9F8HXJtphINRCQDt6sish78Q3ADzvR0GfOK7eQvbs8IqvIhlS1zRixzeRrY27B2nXpxELd0oLzCFaLnM5aKlFJaP8XnJ889F6C6u9PwAVjWuT2uIi+57WozgRl5tYlJz3rP/NQmqouKyJUsGQ4s5z3E5xbMJpJkqsb+UESRGMhAMkzKFXkzhHfdC6HHHuqk9TpwtKxZXK5+h0BWuCwDTq9p+/GZ7gl9HoGEq3l0EyqKtrpaGkv+dohbkKwuSECu8iwmyA0a6deTrJu0x/cdkxE6rfJnpO/zG9pkprr2LqQIgqD2aRLF+3Aqhpn4kbTzWwCrrOEwv7PTmqTWAYgb5akfYlpHzGELnna9XDwNwE0k8dBNUy2F77UWLVnN1Sqo+C1bZk6hdfI+mvtEhESj/15vaCY7wNI1WsOLc56UKwnDOElwQzbNOdJp/Uv/Lso3sBylGcxwOSe0U5FYH08RXfgleKewAvcb8A+CmQpYIRm5iQOA7dPmkH44rbGoa1JVJcAICkcbwYSaVxXu3r5h9tbqXGly/30DV22NeWk9SXLTzofiZ83YlkZs1JItLm+EfrjlUKXAOAN2R8ooxLiiGrOF6kV8O2dGl+FYnLk4D3SaKsiXs0FQvhKbtlKUR9v1IUK6GrZ3xo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
